Дополнить проект кодом по заданию 7
VolchenkoP/java-kanban pull request #7
Opened 2024-04-27 09:57 UTC by VolchenkoP

2024-04-28 00:55 UTC, dgumich requested changes

2024-04-28 00:55 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +    private Status checkStatus(String status) {
Правильней назвать метод getStatus.
Кроме это любой класс enum имеет метод valueOf, который по сути сделает то же самое.
Так что используй его.

2024-04-28 00:55 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +    private void readWordsFromFile() {
Больше подойдет для метода подойдет название readTasksFromFile

2024-04-28 00:55 UTC, dgumich commented on src/ru/practicum/tasksManager/exeption/ManagerSaveException.java
> +public class ManagerSaveException extends IOException {
Обычно кастомные исключения наследуют от RunTimeException, что бы не надо было городить блоки try-catch.
Так что поменяй класс-родитель.

2024-04-28 00:55 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +        } catch (ManagerSaveException e) {
Ненене, мы должны ловить IOException, а вместо него бросать наше, кастомное.
То есть должен остаться блок catch на строках 125-127, но вместо new RuntimeException(e) должно быть new ManagerSaveException(e)

2024-04-28 00:55 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +                saveTask(task);
Мы не должны использовать метод saveTask/Epic/SubTask, потому что 
1) Данный метод сохраняет файл. То есть мы только только прочитали из файла и тут же его перезаписываем и сохраняем задачу за задачей. По идее, в конце мы получим точно такой же файл. Чем же это плохо? Тем что может произойти ошибка и тогда мы потеряем оригинальный файл. Кроме этого сами операции чтения/записи дорогие с точки зрения ресурсов, поэтому не надо вызывать их для бесполезной работы.
2) Вторая проблема - перезапись айдишника. Мы считали из файла задачу/подзадачу/эпик с каким-то айди. Вызвали метод  saveTask(task) где ей будет присвоен новый айдишник. А это плохо, пользователь помнит, что задача была с айди 1, а стала, например, с айди 12.

Как сделать? Поменять модификатор доступа у мап с подзадачми, эпиками, задачами в классе родителе и просто класть в них по айди.
Только не забывай, что при чтении из файла, надо найти максимальный айди, увеличить на 1 и присвоить его  счетчику private int countId; из InMemoryTaskManager

2024-04-28 00:55 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +            type = String.valueOf(TypeOfTask.EPIC);
Нет, с типом задачи надо работать по другому: создать поле типа TypeOfTask в Task (по аналогии с полем Status) и при создании задачи/подзадачи/эпика сетапить нужное значение.

2024-04-28 00:55 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +        String name = example.getName();
Надо разделить логику парсинга задачи/подзадачи/эпика в строку и его запись в файл.
В ТЗ даже есть подсказка по этому поводу:
Напишите метод сохранения задачи в строку String toString(Task task) или переопределите базовый.
Напишите метод создания задачи из строки Task fromString(String value).

2024-04-28 00:55 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +        } catch (ManagerSaveException e) {
Так же не правильно сделано ловля исключения. Мы должны ловить IOException e, а бросать ManagerSaveException

2024-04-28 00:55 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +            BufferedWriter writer = new BufferedWriter(new FileWriter(fileToHistory));
Открывать/закрывать ресурсы для записи надо стараться как можно реже. 
В данном случае надо сделать всю запись в файл в одном writer

2024-04-28 00:55 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +        allTasks.addAll(this.getTasks());
Бесполезная логика: мы берем все задачи/подзадачи/эпики, кладем в один лист, что бы потом пройтись по этому листу.
Мы можем обойтись без копирования, сразу пройтись по листу с задачами, эпиками и подздадачами.

2024-04-28 00:55 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +        for (Task task : allTasks) {
Надо исправить логику метода save:
создаем райтер, записываем верхнюю строку.
В этом же блоке трай берем лист с задачами, итерируемся по нему и записываем каждую задачу:
райтер.райт(конвертТаскТуСтринг(таск)
Потом так же итерируемся по эпикам и подзадачам.
Метод получится короткий и понятной логикой.

2024-04-28 00:55 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +    public FileBackedTaskManager(File file) {
По ТЗ создание экземпляра класса должно происходить через статический метод:
Кроме метода сохранения, создайте статический метод static FileBackedTaskManager loadFromFile(File file), который будет восстанавливать данные менеджера из файла при запуске программы.

2024-04-28 00:55 UTC, dgumich commented on test/ru/practicum/tasksManager/service/impl/FileBackedTaskManagerTest.java
> +    @Test
Молодец, что используешь юнит тестирование, хотя еще не проходили.
Но при использовании сторонних библиотек добавляй их в проект, что бы не приходилось их скачивать.
Я же не знаю, какую версию ты используешь=)

2024-04-28 00:55 UTC, dgumich commented on test/ru/practicum/tasksManager/service/impl/FileBackedTaskManagerTest.java
> +    File file;
В тестах такие же правила по код стайлу как и в коде: поля должны быть приватными.

2024-05-02 13:35 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +    private Status checkStatus(String status) {
поправил

2024-05-02 13:35 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +    private void readWordsFromFile() {
поправил

2024-05-02 13:35 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/exeption/ManagerSaveException.java
> +public class ManagerSaveException extends IOException {
поправил

2024-05-02 13:36 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +        } catch (ManagerSaveException e) {
вроде, поправил...

2024-05-02 13:36 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +                saveTask(task);
поправил

2024-05-02 14:33 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +        allTasks.addAll(this.getTasks());
поправил

2024-05-02 14:34 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +        for (Task task : allTasks) {
поправил

2024-05-02 14:34 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +    public FileBackedTaskManager(File file) {
поправил

2024-05-02 14:34 UTC, VolchenkoP commented on test/ru/practicum/tasksManager/service/impl/FileBackedTaskManagerTest.java
> +    @Test
убрал из гитигнора джар фалы юнита

2024-05-02 14:34 UTC, VolchenkoP commented on test/ru/practicum/tasksManager/service/impl/FileBackedTaskManagerTest.java
> +    File file;
поправил

2024-05-03 01:32 UTC, dgumich requested changes

2024-05-03 01:32 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    static int countId;
А зачем делать счётчик статичны? Сделай обычным полем=)

2024-05-03 01:32 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +        if (getSubtasks().contains(example)) {
Не самая эффективная логика - берём все подзадачи и проходим по ним в поиске нужной. Это может быть долго. Тебе же только надо понять, что это подзадача. И как удобно у нас есть поле - TypeOfTask по которому мы можем сразу понять, что за тип задачи. Используй его.

2024-05-03 01:32 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +                for (Subtask subtask : subtasks.values()) {
Молодец, что добавил логику проверки подзадач, во время считывания эпика.

2024-05-03 01:32 UTC, dgumich commented on test/ru/practicum/tasksManager/service/impl/FileBackedTaskManagerTest.java
> +    {
Тут ок, так как тесты еще не проходили, но вообще есть специальные методы из Junit библиотеки, которые как раз используются для настройки тестов. Так что никаких блоков не нужно=)

2024-05-03 01:32 UTC, dgumich commented on test/ru/practicum/tasksManager/service/impl/FileBackedTaskManagerTest.java
> +    void addNewEpic() {
Не совсем корректное название тестовых методов, но это ок, потому что еще не проходили. Можешь больше прочитать про это здесь https://www.baeldung.com/java-unit-testing-best-practices

2024-05-03 07:28 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    static int countId;
забыл поправить, тут ошибочно ушел в реализацию статического метода со статическими полями, потом все вернул, кроме этого поля. Поправил.

2024-05-03 07:28 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/FileBackedTaskManager.java
> +        if (getSubtasks().contains(example)) {
Точно, поправил.

2024-05-03 07:46 UTC, merged