Добавить код по заданию 8
VolchenkoP/java-kanban pull request #8
Opened 2024-05-15 11:09 UTC by VolchenkoP

2024-05-15 23:22 UTC, dgumich requested changes

2024-05-15 23:22 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +            epics.values().stream()
Зачем поменял на стрим? Понимаешь, что сделал только хуже? Вместо того, что бы из конкретной мапы по айди взять эпик мы итерируемся по листу с эпиками, ищем подходящий и потом добавляем. И код стал хуже выглядеть и время работы увеличили. Верни как было

2024-05-15 23:22 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    public Optional<Task> getTaskById(int id) {
Зачем сделал, что бы метод стал возвращать опшинал? Это не правильно по тз. Верни как было.

2024-05-15 23:22 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
>      public void deleteById(int id) {
Этот метод надо разбить на три:
deleteTaskById
deleteSubTaskById
deleteEpicById

2024-05-15 23:22 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +                    .filter(subtask -> subtask.equals(subtasks.get(id)))
Рефакторинг от которого стало только хуже=(

2024-05-15 23:22 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +        tasks.values().stream()
Аналогично, не нужно никакого стрима.
Так же перед апдейтом надо проверить, что по данном айди у нас есть задача (у мапы есть для этого метод).
Если есть - обновляем (можно обновить поля, но более быстрое просто сделать put(id, task)), если ничего по такому ключу нет - ничего не делаем, потому что обновлять нечего.

2024-05-15 23:22 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    public Set<Task> getPrioritizedTasks() {
Должны возвращать лист, а не сет

2024-05-15 23:22 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    boolean checkTimeCrossing(Task task1, Task task2) {
Метод должен быть приватным

2024-05-15 23:22 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    void addToTasksByStartTimeTreeSet(Task task) {
Метод должен быть приватным

2024-05-15 23:22 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
>      void changeEpicStatus(Epic epic) {
Метод должен быть приватным

2024-05-15 23:22 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    void changeEpicEndTime(Epic epic) {
Метод должен быть приватным, так как внутренняя логика класса.

2024-05-15 23:22 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    boolean validateStartTimeForTask(Task task) {
Метод должен быть приватным

2024-05-15 23:22 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +                .map(someTask -> {
При апдейтах надо так же проверять пересечение задач по времени.

2024-05-16 11:23 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +            epics.values().stream()
поправил, не совсем понял требования убрать из кода все временные ссылки. Скорее всего имелось в виду только в местах, где есть  циклы.

2024-05-16 11:25 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    public Optional<Task> getTaskById(int id) {
доп задание попытался сделать
<img width="738" alt="image" src="https://github.com/VolchenkoP/java-kanban/assets/160169878/15af43c8-bf01-4102-bc9f-46b0b6afaaa9">

2024-05-16 11:25 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
>      public void deleteById(int id) {
разбил

2024-05-16 11:25 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +        tasks.values().stream()
поправил

2024-05-16 11:25 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +                    .filter(subtask -> subtask.equals(subtasks.get(id)))
выше дал коммент, поправил.

2024-05-16 11:26 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    public Set<Task> getPrioritizedTasks() {
поправил

2024-05-16 11:26 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    boolean checkTimeCrossing(Task task1, Task task2) {
в этом месте поправил, но пришлось сделать публичный метод для вызова в другом классе (для сборки из файла)

2024-05-16 11:27 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    void addToTasksByStartTimeTreeSet(Task task) {
поправил

2024-05-16 11:28 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
>      void changeEpicStatus(Epic epic) {
аналогично с методом смены времени

2024-05-16 11:28 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    void changeEpicEndTime(Epic epic) {
аналогично с методом выше

2024-05-16 11:28 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    boolean validateStartTimeForTask(Task task) {
поправил

2024-05-16 11:29 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +                .map(someTask -> {
поправил

2024-05-17 00:05 UTC, dgumich requested changes

2024-05-17 00:05 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +            taskLink.setName(task.getName());
А зачем так сетапишь поля? Не проще ли просто положить обновленную задачу по айди и всё? То есть просто tasks.put(task.getId(), task)? Экономия многих строчек кода, а результат такой же=)

2024-05-17 00:05 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
>          return countId;
Нам точно не нужен этот метод, да еще публичный. Удали из менеджера и интерфейса.

2024-05-17 00:05 UTC, dgumich commented on test/ru/practicum/tasksManager/service/impl/InMemoryHistoryManagerTest.java
> +    void shouldReturnEmptyHistoryListAfterDeleteTaskAfterSave() {
Смотри, юнит тестирование - это тестирование метода. Исходя из этого строится его название и логика.
Здесь мы хотим протестить метод удалить из истории (removeFromHistory).  С логикой всё ок - добавили задачу, потом удалили и проверили, что удалена. Но вот название должно быть другим. Принцип построения названия:
test(или в начале или в конце, думаю, понятно зачем это слово) + метод, который тестируем + кейс, который тестируем. В данном случае получится: testRemoveFromHistoryShouldSuccesffulyRemoveTaskFromHistory.
По такой аналогии надо поменять названия методов у всех тестов. 
Здесь можешь почитать про бест практис в юнит тестировании 
https://www.baeldung.com/java-unit-testing-best-practices

2024-05-17 00:05 UTC, dgumich commented on test/ru/practicum/tasksManager/service/impl/FileBackedTaskManagerTest.java
> +    FileBackedTaskManager fileBackedTaskManager;
Поле так же должно быть приватным

2024-05-17 00:05 UTC, dgumich commented on test/ru/practicum/tasksManager/service/impl/TaskManagerTest.java
> +    HistoryManager historyManager;
Не, хистори менджера здесь вообще не должно быть. У него отдельный тестовый класс, где мы его тестим.

2024-05-17 00:05 UTC, dgumich commented on test/ru/practicum/tasksManager/service/impl/TaskManagerTest.java
> +        taskManager = Managers.getDefault();
Логика сделана не правильно. В чём смысл создания абстрактно тестового класса и затем наследников?
Дело в том, что методы в данных классах одни и те же. Логика их тестирования тоже. То есть нам не надо полностью писать тесты для InMemoryTaskManager и  FileBackedTaskManager.
Как делаем: пишем тесты в абстрактном классе. А сам менджер (taskManager) создаем в классе наследнике. Если это ин мемори - там создаем ин мемори менджера. Если файл менджер - файл менджер. 
У тебя же просто есть абстрактный класс, который никак не связан с наследниками, потому что менджер создаешь в каждом методе с помощью Managers.getDefault().

2024-05-17 00:05 UTC, dgumich commented on test/ru/practicum/tasksManager/service/impl/InMemoryTaskManagerTest.java
>      @Test
В данном классе остались странные тесты, который вообще не проверяют работу InMemoryTaskManager и никак к нему не относятся.

2024-05-17 00:08 UTC, dgumich commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +    public Optional<Task> getTaskById(int id) {
Понял, мог не удалять, раз по заданию сделал=)

2024-05-18 16:35 UTC, VolchenkoP commented on src/ru/practicum/tasksManager/service/impl/InMemoryTaskManager.java
> +            taskLink.setName(task.getName());
поправил, но если просто укладывать, то с перерасчетом эпика все равно приходится костыли вешать через ремув и пут

2024-05-18 16:35 UTC, VolchenkoP commented on test/ru/practicum/tasksManager/service/impl/InMemoryHistoryManagerTest.java
> +    void shouldReturnEmptyHistoryListAfterDeleteTaskAfterSave() {
переделал полностью все тесты, надеюсь понял получше)))

2024-05-18 16:36 UTC, VolchenkoP commented on test/ru/practicum/tasksManager/service/impl/FileBackedTaskManagerTest.java
> +    FileBackedTaskManager fileBackedTaskManager;
переделал

2024-05-18 16:36 UTC, VolchenkoP commented on test/ru/practicum/tasksManager/service/impl/TaskManagerTest.java
> +    HistoryManager historyManager;
переделал

2024-05-18 16:36 UTC, VolchenkoP commented on test/ru/practicum/tasksManager/service/impl/TaskManagerTest.java
> +        taskManager = Managers.getDefault();
переделал

2024-05-18 16:36 UTC, VolchenkoP commented on test/ru/practicum/tasksManager/service/impl/InMemoryTaskManagerTest.java
>      @Test
переделал

2024-05-18 19:26 UTC, dgumich approved these changes

2024-05-18 19:28 UTC, merged